package com.raitichan.raitismodcore;

import com.raitichan.raitismodcore.register.Register;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

/**
 * Raiti's Mod Core 読み込みクラス
 * <br>Created by Raiti-chan on 2017/10/29.
 *
 * @author Raiti-chan
 * @version 1.0.0
 * @since 1.0.0
 */
@SuppressWarnings({"WeakerAccess", "unused"})
@Mod(modid = RaitisModCore.MOD_ID, name = RaitisModCore.MOD_NAME, version = RaitisModCore.VERSION, useMetadata = true)
public class RaitisModCore {
	
	/**
	 * MOD ID
	 */
	@SuppressWarnings("WeakerAccess")
	public static final String MOD_ID = "RaitisModCore";
	
	/**
	 * MOD Name
	 */
	@SuppressWarnings("WeakerAccess")
	public static final String MOD_NAME = "Raiti's Mod Core";
	
	/**
	 * MOD Version
	 */
	@SuppressWarnings("WeakerAccess")
	public static final String VERSION = "1.0.0 a_3";
	
	/**
	 * MOD Metadata
	 */
	@Mod.Metadata
	public static ModMetadata METADATA;
	
	//プロキシ―
	
	//==================================================================================================================
	
	/**
	 * Pre Init
	 * @param event FMLEvent
	 */
	@Mod.EventHandler
	public void perinit(FMLPreInitializationEvent event) {
		loadMeta(METADATA);
		System.out.println("Loading Raiti'sModCore:PreInit");
		Register.register(Register.getInstance());
	}
	
	
	/**
	 * Init
	 * @param event FMLEvent
	 */
	@Mod.EventHandler
	public void init(FMLInitializationEvent event) {
		System.out.println("Loading Raiti'sModCore:Init");
	}
	
	
	/**
	 * Post Init
	 * @param event FMLEvent
	 */
	@Mod.EventHandler
	public void postinit(FMLPostInitializationEvent event) {
		System.out.println("Loading Raiti'sModCore:PostInit");
	}
	
	//==================================================================================================================
	
	private void loadMeta(ModMetadata metadata) {
		metadata.modId = MOD_ID;
		metadata.name = MOD_NAME;
		metadata.version = VERSION;
		metadata.authorList.add("Raiti-chan");
		metadata.description = "Raiti's Mod Core";
		metadata.autogenerated = false;
	}
}
